export const shopifyStores = [
  {
    id: 1,
    storeName: 'FitnessGearShop',
    currentPlan: 'Basic',
    appStatus: 'Installed',
    installedAt: '2023-06-15T14:32:00Z',
  },
  {
    id: 2,
    storeName: 'TechGizmos',
    currentPlan: 'Advanced',
    appStatus: 'Uninstalled',
    installedAt: '2022-11-25T10:20:00Z',
  },
  {
    id: 3,
    storeName: 'EcoProductsStore',
    currentPlan: 'Shopify Plus',
    appStatus: 'Installed',
    installedAt: '2023-01-07T08:50:00Z',
  },
  {
    id: 4,
    storeName: 'HomeDecorEmpire',
    currentPlan: 'Basic',
    appStatus: 'Uninstalled',
    installedAt: '2022-09-12T18:12:00Z',
  },
  {
    id: 5,
    storeName: 'GourmetFoods',
    currentPlan: 'Advanced',
    appStatus: 'Installed',
    installedAt: '2023-03-22T09:05:00Z',
  },
  {
    id: 6,
    storeName: 'SportsHaven',
    currentPlan: 'Shopify Plus',
    appStatus: 'Installed',
    installedAt: '2024-01-10T15:30:00Z',
  },
  {
    id: 7,
    storeName: 'LuxuryWatches',
    currentPlan: 'Basic',
    appStatus: 'Uninstalled',
    installedAt: '2022-07-19T11:45:00Z',
  },
  {
    id: 8,
    storeName: 'BeautyEssentials',
    currentPlan: 'Advanced',
    appStatus: 'Installed',
    installedAt: '2023-05-02T13:20:00Z',
  },
  {
    id: 9,
    storeName: 'ArtisanCrafts',
    currentPlan: 'Basic',
    appStatus: 'Installed',
    installedAt: '2022-10-04T16:35:00Z',
  },
  {
    id: 10,
    storeName: 'PetCareSupplies',
    currentPlan: 'Shopify Plus',
    appStatus: 'Uninstalled',
    installedAt: '2023-02-18T12:00:00Z',
  },
];
